import {
  AUTH_ACTION,
  APP_ACTION,
  LISTING_ACTION,
  PROGRESS_ACTION,
  PAYMENT_ACTION,
  COMMUNICATION_ACTION,
} from '../actionTypes';
import appState from '../states/appState';

const appReducer = (state = appState.initState, action) => {
  switch (action.type) {
    // START REQUEST
    case AUTH_ACTION.SELECT_ACCOUNT:
    case AUTH_ACTION.CUSTOMER_LOGIN:
    case AUTH_ACTION.UPDATE_PROFILE:
    case LISTING_ACTION.GET_ADDRESS_DATA:
    case LISTING_ACTION.GET_DISTANCE_MATRIX:
    case LISTING_ACTION.GET_ADVERT_DESCRIPTION:
    case LISTING_ACTION.SAVE_LISTING_ITEMS:
    case LISTING_ACTION.REQUEST_BOOK_NOW:
    case LISTING_ACTION.LISTING_ITEMS_GET_QUOTE:
    case LISTING_ACTION.HANDLE_SEND:
    case LISTING_ACTION.SAVE_ADDRESS_AS_DRAFT:
    case LISTING_ACTION.SAVE_ADDRESS_QUOTE:
    case LISTING_ACTION.UN_LIST:
    case LISTING_ACTION.UPLOAD_PHOTO_SHIPMENT:
    case LISTING_ACTION.DELETE_PHOTO_SHIPMENT:
    case LISTING_ACTION.EDIT_DESTINATION_ADDRESS:
    case LISTING_ACTION.EDIT_PICKUP_ADDRESS:
    case LISTING_ACTION.REDIRECT_MANAGEMENT_SHIPMENTS:
    case LISTING_ACTION.SET_FIELD_QUERY:
    case LISTING_ACTION.GET_SHIPMENT_DETAILS:
    case PROGRESS_ACTION.GET_PROGRESS:
    case PROGRESS_ACTION.DELETE_PROGRESS_ATTACHMENT:
    case PROGRESS_ACTION.UPLOAD_DISPATCHED_ATTACHMENT:
    case PROGRESS_ACTION.UPLOAD_PROGRESS_ATTACHMENT:
    case PAYMENT_ACTION.UPLOAD_PROOF_PAYMENT_METHOD:
    case COMMUNICATION_ACTION.SEND_ATTACHMENT:
    case COMMUNICATION_ACTION.DOWNLOAD_DATA:
    case PAYMENT_ACTION.DELETE_PROOF_PAYMENT_METHOD:
      return {
        ...state,
        isLoading: true,
      };
    // REQUEST SUCCESS
    case AUTH_ACTION.CUSTOMER_LOGIN_SUCCESS:
    case AUTH_ACTION.UPDATE_PROFILE_SUCCESS:
    case LISTING_ACTION.GET_ADDRESS_DATA_SUCCESS:
    case LISTING_ACTION.GET_DISTANCE_MATRIX_SUCCESS:
    case LISTING_ACTION.UPDATE_SHIPMENT_SUCCESS:
    case LISTING_ACTION.REQUEST_BOOK_NOW_SUCCESS:
    case LISTING_ACTION.LISTING_ITEMS_GET_QUOTE_SUCCESS:
    case LISTING_ACTION.HANDLE_SEND_SUCCESS:
    case LISTING_ACTION.SAVE_ADDRESS_AS_DRAFT_SUCCESS:
    case LISTING_ACTION.SAVE_ADDRESS_QUOTE_SUCCESS:
    case LISTING_ACTION.GET_ADDITIONAL_SERVICES_SUCCESS:
    case LISTING_ACTION.UN_LIST_SUCCESS:
    case LISTING_ACTION.UPLOAD_PHOTO_SHIPMENT_SUCCESS:
    case LISTING_ACTION.DELETE_PHOTO_SHIPMENT_SUCCESS:
    case LISTING_ACTION.SET_DATA_FOR_QUERY_SUCCESS:
    case LISTING_ACTION.GET_LIST_SHIPMENTS_SUCCESS:
    case LISTING_ACTION.GET_SHIPMENT_DETAILS_SUCCESS:
    case PROGRESS_ACTION.GET_PROGRESS_SUCCESS:
    case PROGRESS_ACTION.UPLOAD_DISPATCHED_ATTACHMENT_SUCCESS:
    case PROGRESS_ACTION.UPLOAD_PROGRESS_ATTACHMENT_SUCCESS:
    case LISTING_ACTION.REDIRECT_MANAGEMENT_SHIPMENTS_SUCCESS:
    case PAYMENT_ACTION.UPLOAD_PROOF_PAYMENT_METHOD_SUCCESS:
    case COMMUNICATION_ACTION.SEND_ATTACHMENT_SUCCESS:
    case COMMUNICATION_ACTION.DOWNLOAD_DATA_SUCCESS:
    case PAYMENT_ACTION.DELETE_PROOF_PAYMENT_METHOD_SUCCESS:
      return {
        ...state,
        ...appState.setRequestSuccess()
      };
    // REQUEST FAILURE
    case AUTH_ACTION.SELECT_ACCOUNT_FAILURE:
    case AUTH_ACTION.CUSTOMER_LOGIN_FAILURE:
    case AUTH_ACTION.UPDATE_PROFILE_FAILURE:
    case LISTING_ACTION.GET_ADDRESS_DATA_FAILURE:
    case LISTING_ACTION.GET_DISTANCE_MATRIX_FAILURE:
    case LISTING_ACTION.GET_ADVERT_DESCRIPTION_FAILURE:
    case LISTING_ACTION.SAVE_LISTING_ITEMS_FAILURE:
    case LISTING_ACTION.UPDATE_SHIPMENT_FAILURE:
    case LISTING_ACTION.REQUEST_BOOK_NOW_FAILURE:
    case LISTING_ACTION.LISTING_ITEMS_GET_QUOTE_FAILED:
    case LISTING_ACTION.LISTING_ADDRESSES_GET_QUOTE_FAILED:
    case LISTING_ACTION.HANDLE_SEND_FAILED:
    case LISTING_ACTION.SAVE_ADDRESS_AS_DRAFT_FAILED:
    case LISTING_ACTION.SAVE_ADDRESS_QUOTE_FAILED:
    case LISTING_ACTION.UN_LIST_FAILED:
    case LISTING_ACTION.UPLOAD_PHOTO_SHIPMENT_FAIL:
    case LISTING_ACTION.DELETE_PHOTO_SHIPMENT_FAIL:
    case LISTING_ACTION.EDIT_PICKUP_ADDRESS_FAIL:
    case LISTING_ACTION.SAVE_LISTING_ADDRESS_FAILURE:
    case LISTING_ACTION.SET_DATA_FOR_QUERY_FAIL:
    case LISTING_ACTION.GET_LIST_SHIPMENTS_FAIL:
    case LISTING_ACTION.GET_SHIPMENT_DETAILS_FAILURE:
    case LISTING_ACTION.REDIRECT_MANAGEMENT_SHIPMENTS_FAIL:
    case LISTING_ACTION.LISTING_SAVE_DRAFT_FAILED:
    case LISTING_ACTION.REJECT_QUOTE_FAIL:
    case LISTING_ACTION.CANCEL_BOOKING_FAIL:
    case PROGRESS_ACTION.GET_PROGRESS_FAIL:
    case PROGRESS_ACTION.UPLOAD_DISPATCHED_ATTACHMENT_FAIL:
    case PROGRESS_ACTION.UPLOAD_PROGRESS_ATTACHMENT_FAIL:
    case PAYMENT_ACTION.REQUEST_CHANGE_PAYMENT_METHOD_FAILED:
    case PAYMENT_ACTION.AMEND_PAYMENT_METHOD_FAILED:
    case PAYMENT_ACTION.UPLOAD_PROOF_PAYMENT_METHOD_FAILED:
    case PAYMENT_ACTION.GET_PAYMENT_FAILED:
    case PAYMENT_ACTION.DELETE_PROOF_PAYMENT_METHOD_FAILED:
      return {
        ...state,
        ...appState.setRequestFailse(action.error)
      };
    // UPDATE BASIC FIELD
    case APP_ACTION.CHANGE_COUNTRY_SUCCESS:
      return {
        ...state,
        ...action.payload,
      };
    case APP_ACTION.SET_APP_DATA:
      return {
        ...state,
        ...action.payload,
      };
    case APP_ACTION.UPDATE_POSITION:
      return {
        ...state,
        ...action.payload,
      };
    case AUTH_ACTION.SELECT_ACCOUNT_SUCCESS:
      return {
        ...state,
        // countryCode: action.countryCode,
        // countryIndex: action.countryIndex || state.countryIndex,
        callingCode: action.callingCode || state.callingCode,
        ...appState.setRequestSuccess()
      };
    case APP_ACTION.REQUIRE_LOGIN_PAGE:
      return {
        ...state,
        ...appState.setPageRequiredName(action.pageRequiredName),
      };
    case APP_ACTION.OPEN_MODAL:
      return {
        ...state,
        modalStatus: action.modalStatus,
        modalData: action.modalData,
      };
    case APP_ACTION.OPEN_ADDRESS_MODAL:
      return {
        ...state,
        openAddressModal: true,
      };
    case LISTING_ACTION.HANDLE_AFTER_EDIT_PICKUP_ADDRESS_FAIL:
    case LISTING_ACTION.HANDLE_AFTER_EDIT_PICKUP_ADDRESS_SUCCESS:
    case LISTING_ACTION.HANDLE_AFTER_EDIT_DESTINATION_ADDRESS_FAIL:
    case LISTING_ACTION.HANDLE_AFTER_EDIT_DESTINATION_ADDRESS_SUCCESS:
      return {
        ...state,
        isLoading: false,
        openAddressModal: false,
      };
    case APP_ACTION.CLOSE_ADDRESS_MODAL:
      return {
        ...state,
        openAddressModal: false,
      };
    // CLOSE MODAL
    case LISTING_ACTION.UPDATE_PICKUP_ADDRESS:
    case LISTING_ACTION.UPDATE_DESTINATION_ADDRESS:
    case APP_ACTION.CLOSE_MODAL:
      return {
        ...state,
        ...appState.closeModal(),
      };
    case APP_ACTION.UPDATE_LANGUAGE:
      return {
        ...state,
        updatingCountry: {
          ...state.updatingCountry,
          ...action.payload,
        },
      };
    case LISTING_ACTION.GET_ADVERT_DESCRIPTION_SUCCESS:
      return {
        ...state,
        isLoading: false,
        errorMessage: action.errorMessage,
      };
    case APP_ACTION.GET_CONFIGURATION_APP_SUCCESS:
      return {
        ...state,
        configs: action.data,
      };
    case APP_ACTION.CLEAR_ERROR:
      return {
        ...state,
        errorMessage: null,
      };
    default:
      return state;
  }
};

export default appReducer;
