export const AUTH_ACTION = {
  DRIVER_LOGIN: 'DRIVER_LOGIN',
  DRIVER_LOGIN_SUCCESS: 'DRIVER_LOGIN_SUCCESS',
  DRIVER_LOGIN_FAILURE: 'DRIVER_LOGIN_FAILURE',
  LOG_OUT: 'DRIVER_LOGOUT'
};

export const APP_ACTION = {
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN',
  TOGGLE_DROPDOWN_FILTER: 'TOGGLE_DROPDOWN_FILTER',
  CLEAR_ERROR: 'CLEAR_ERROR',
  SAVE_CONFIG: 'SAVE_CONFIG',
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  TOGGLE_DROPDOWN_ADDRESS: 'TOGGLE_DROPDOWN_ADDRESS'
};

export const SHIPMENT_ACTION = {
  GET_HANDLE_UNIT: 'GET_HANDLE_UNIT',
  GET_HANDLE_UNIT_SUCCESS: 'GET_HANDLE_UNIT_SUCCESS',
  GET_HANDLE_UNIT_FAILED: 'GET_HANDLE_UNIT_FAILED',

  GET_LOCATION_TYPE: 'GET_LOCATION_TYPE',
  GET_LOCATION_TYPE_SUCCESS: 'GET_LOCATION_TYPE_SUCCESS',
  GET_LOCATION_TYPE_FAILED: 'GET_LOCATION_TYPE_FAILED',

  SET_SHIPMENT_DETAILS: 'SET_SHIPMENT_DETAILS',
  SET_SHIPMENT_DETAILS_SUCCESS: 'SET_SHIPMENT_DETAILS_SUCCESS',
  SET_SHIPMENT_DETAILS_FAIL: 'SET_SHIPMENT_DETAILS_FAIL',

  SET_QUOTE_DETAIL: 'SET_QUOTE_DETAIL',
  SET_QUOTE_DETAIL_SUCCESS: 'SET_QUOTE_DETAIL_SUCCESS',
  SET_QUOTE_DETAIL_FAIL: 'SET_QUOTE_DETAIL_FAIL',
  SET_QUOTE_DETAIL_SORT: 'SET_QUOTE_DETAIL_SORT',

  // LOAD MORE
  SET_LOAD_MORE_QUOTE_DETAIL: 'SET_LOAD_MORE_QUOTE_DETAIL',
  SET_LOAD_MORE_QUOTE_DETAIL_SUCCESS: 'SET_LOAD_MORE_QUOTE_DETAIL_SUCCESS',
  SET_LOAD_MORE_QUOTE_DETAIL_FAILED: 'SET_LOAD_MORE_QUOTE_DETAIL_FAILED',

  CREATE_QUOTE: 'CREATE_QUOTE',
  CREATE_QUOTE_SUCCESS: 'CREATE_QUOTE_SUCCESS',
  CREATE_QUOTE_FAILED: 'CREATE_QUOTE_FAILED'
};

export const DRIVER_ACTION = {
  // PICKUP FILTER
  SET_DATA_ROOT_PICKUP: 'SET_DATA_ROOT_PICKUP',
  SET_DATA_ROOT_PICKUP_SUCCESS: 'SET_DATA_ROOT_PICKUP_SUCCESS',
  SET_DATA_ROOT_PICKUP_FAIL: 'SET_DATA_ROOT_PICKUP_FAIL',

  SET_COORS_ADDRESS: 'SET_COORS_ADDRESS',
  SET_COORS_ADDRESS_SUCCESS: 'SET_COORS_ADDRESS_SUCCESS',
  SET_COORS_ADDRESS_FAIL: 'SET_COORS_ADDRESS_FAIL',

  SET_DATA_ANOTHER_PICKUP: 'SET_DATA_ANOTHER_PICKUP',
  SET_DATA_ANOTHER_PICKUP_SUCCESS: 'SET_DATA_ANOTHER_PICKUP_SUCCESS',
  SET_DATA_ANOTHER_PICKUP_FAIL: 'SET_DATA_ANOTHER_PICKUP_FAIL',

  REMOVE_PICKUP_ADDRESS: 'REMOVE_PICKUP_ADDRESS',
  REMOVE_PICKUP_ADDRESS_SUCCESS: 'REMOVE_PICKUP_ADDRESS_SUCCESS',
  REMOVE_PICKUP_ADDRESS_FAIL: 'REMOVE_PICKUP_ADDRESS_FAIL',

  // DELIVERY FILTER
  SET_DATA_ROOT_DELIVERY: 'SET_DATA_ROOT_DELIVERY',
  SET_DATA_ROOT_DELIVERY_SUCCESS: 'SET_DATA_ROOT_DELIVERY_SUCCESS',
  SET_DATA_ROOT_DELIVERY_FAIL: 'SET_DATA_ROOT_DELIVERY_FAIL',

  SET_DATA_ANOTHER_DELIVERY: 'SET_DATA_ANOTHER_DELIVERY',
  SET_DATA_ANOTHER_DELIVERY_SUCCESS: 'SET_DATA_ANOTHER_DELIVERY_SUCCESS',
  SET_DATA_ANOTHER_DELIVERY_FAIL: 'SET_DATA_ANOTHER_DELIVERY_FAIL',

  REMOVE_DELIVERY_ADDRESS: 'REMOVE_DELIVERY_ADDRESS',
  REMOVE_DELIVERY_ADDRESS_SUCCESS: 'REMOVE_DELIVERY_ADDRESS_SUCCESS',
  REMOVE_DELIVERY_ADDRESS_FAIL: 'REMOVE_DELIVERY_ADDRESS_FAIL',

  SET_FIELD_SEARCH_SHIPMENT_BY_DRIVER: 'SET_FIELD_SEARCH_SHIPMENT_BY_DRIVER',
  SET_FIELD_SEARCH_SHIPMENT_BY_DRIVER_FAILURE: 'SET_FIELD_SEARCH_SHIPMENT_BY_DRIVER_FAILURE',
  SET_FIELD_SEARCH_SHIPMENT_BY_DRIVER_SUCCESS: 'SET_FIELD_SEARCH_SHIPMENT_BY_DRIVER_SUCCESS',

  SET_DATA_FOR_QUERY: 'SET_DATA_FOR_QUERY',
  SET_DATA_FOR_QUERY_SUCCESS: 'SET_DATA_FOR_QUERY_SUCCESS',
  SET_DATA_FOR_QUERY_FAIL: 'SET_DATA_FOR_QUERY_FAIL',

  SET_FIELD_QUERY: 'SET_FIELD_QUERY',
  SET_FIELD_QUERY_SUCCESS: 'SET_FIELD_QUERY_SUCCESS',
  SET_FIELD_QUERY_FAIL: 'SET_FIELD_QUERY_FAIL',

  SET_RADIUS_FOR_ADDRESS: 'SET_RADIUS_FOR_ADDRESS',
  SET_RADIUS_FOR_ADDRESS_SUCCESS: 'SET_RADIUS_FOR_ADDRESS_SUCCESS',
  SET_RADIUS_FOR_ADDRESS_FAIL: 'SET_RADIUS_FOR_ADDRESS_FAIL',

  // LOAD MORE
  SET_LOAD_MORE: 'SET_LOAD_MORE',
  SET_LOAD_MORE_SUCCESS: 'SET_LOAD_MORE_SUCCESS',
  SET_LOAD_MORE_FAILED: 'SET_LOAD_MORE_FAILED',

  SET_PIN: 'SET_PIN',
  SET_PIN_SUCCESS: 'SET_PIN_SUCCESS',
  SET_PIN_FAILED: 'SET_PIN_FAILED',

  SELECT_SHIPMENT: 'SELECT_SHIPMENT',
  SELECT_SORT_ITEM: 'SELECT_SORT_ITEM',
  SELECT_FILTER_ITEM: 'SELECT_FILTER_ITEM',

  CHANGE_LIST_VIEW_TYPE: 'CHANGE_LIST_VIEW_TYPE',

  GET_TOP_LOWEST_BID: 'GET_TOP_LOWEST_BID',
  GET_TOP_LOWEST_BID_SUCCESS: 'GET_TOP_LOWEST_BID_SUCCESS',
  GET_TOP_LOWEST_BID_FAIL: 'GET_TOP_LOWEST_BID_FAIL',

  GET_TOTAL_STATUS_FILTER: 'GET_TOTAL_STATUS_FILTER',
  GET_TOTAL_STATUS_FILTER_SUCCESS: 'GET_TOTAL_STATUS_FILTER_SUCCESS',
  GET_TOTAL_STATUS_FILTER_FAILED: 'GET_TOTAL_STATUS_FILTER_FAILED',
};

export const PROGRESS_ACTION = {
  CREATE_PROGRESS: 'CREATE_PROGRESS',
  CREATE_PROGRESS_FAIL: 'CREATE_PROGRESS_FAIL',
  CREATE_PROGRESS_SUCCESS: 'CREATE_PROGRESS_SUCCESS',

  UPDATE_PROGRESS: 'UPDATE_PROGRESS',
  UPDATE_PROGRESS_FAIL: 'UPDATE_PROGRESS_FAIL',
  UPDATE_PROGRESS_SUCCESS: 'UPDATE_PROGRESS_SUCCESS',

  GET_PROGRESS: 'GET_PROGRESS',
  GET_PROGRESS_FAIL: 'GET_PROGRESS_FAIL',
  GET_PROGRESS_SUCCESS: 'GET_PROGRESS_SUCCESS',

  UPLOAD_PROGRESS_PHOTO: 'UPLOAD_PROGRESS_PHOTO',
  UPLOAD_PROGRESS_PHOTO_SUCCESS: 'UPLOAD_PROGRESS_PHOTO_SUCCESS',
  UPLOAD_PROGRESS_PHOTO_FAILED: 'UPLOAD_PROGRESS_PHOTO_FAILED',

  REMOVE_PROGRESS_PHOTO: 'REMOVE_PROGRESS_PHOTO',
  REMOVE_PROGRESS_PHOTO_SUCCESS: 'REMOVE_PROGRESS_PHOTO_SUCCESS',
  REMOVE_PROGRESS_PHOTO_FAILED: 'REMOVE_PROGRESS_PHOTO_FAILED',

  UPDATE_ADDRESS_DESTINATION: 'UPDATE_ADDRESS_DESTINATION',
  UPDATE_ADDRESS_DESTINATION_SUCCESS: 'UPDATE_ADDRESS_DESTINATION_SUCCESS',
  UPDATE_ADDRESS_DESTINATION_FAILED: 'UPDATE_ADDRESS_DESTINATION_FAILED',

  CHANGE_CURRENT_PROGRESS: 'CHANGE_CURRENT_PROGRESS',
};

export const CONFIG_ACTION = {
  GET_CONFIG_SETTING: 'GET_CONFIG_SETTING',
  GET_CONFIG_SETTING_SUCCESS: 'GET_CONFIG_SETTING_SUCCESS',
  GET_CONFIG_SETTING_FAILED: 'GET_CONFIG_SETTING_FAILED',

  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE'
};

export const NOTIFICATION_ACTION = {
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  GET_NOTIFICATION_SUCCESS: 'GET_NOTIFICATION_SUCCESS',
  GET_NOTIFICATION_FAILED: 'GET_NOTIFICATION_FAILED',

  GET_NOTIFICATION_LOAD_MORE: 'GET_NOTIFICATION_LOAD_MORE',
  GET_NOTIFICATION_LOAD_MORE_SUCCESS: 'GET_NOTIFICATION_LOAD_MORE_SUCCESS',
  GET_NOTIFICATION_LOAD_MORE_FAILED: 'GET_NOTIFICATION_LOAD_MORE_FAILED',

  GET_NOTIFICATION_DETAIL: 'GET_NOTIFICATION_DETAIL',
  GET_NOTIFICATION_DETAIL_SUCCESS: 'GET_NOTIFICATION_DETAIL_SUCCESS',
  GET_NOTIFICATION_DETAIL_FAILED: 'GET_NOTIFICATION_DETAIL_FAILED',

  MARK_AS_READ_NOTIFICATION: 'MARK_AS_READ_NOTIFICATION',
  MARK_AS_READ_NOTIFICATION_SUCCESS: 'MARK_AS_READ_NOTIFICATION_SUCCESS',
  MARK_AS_READ_NOTIFICATION_FAILED: 'MARK_AS_READ_NOTIFICATION_FAILED',

  GET_TOTAL_UNREAD_NOTIFICATION: 'GET_TOTAL_UNREAD_NOTIFICATION',
  GET_TOTAL_UNREAD_NOTIFICATION_SUCCESS: 'GET_TOTAL_UNREAD_NOTIFICATION_SUCCESS',
  GET_TOTAL_UNREAD_NOTIFICATION_FAILED: 'GET_TOTAL_UNREAD_NOTIFICATION_FAILED',
};

export const PAYMENT_ACTION = {
  GET_PAYMENT_INFORMATION: 'GET_PAYMENT_INFORMATION',
  GET_PAYMENT_INFORMATION_SUCCESS: 'GET_PAYMENT_INFORMATION_SUCCESS',
  GET_PAYMENT_INFORMATION_FAILED: 'GET_PAYMENT_INFORMATION_FAILED',

  UPDATE_BANK_INSTRUCTIONS: 'UPDATE_BANK_INSTRUCTIONS',
  UPDATE_BANK_INSTRUCTIONS_SUCCESS: 'UPDATE_BANK_INSTRUCTIONS_SUCCESS',
  UPDATE_BANK_INSTRUCTIONS_FAILED: 'UPDATE_BANK_INSTRUCTIONS_FAILED',

  PAYMENT_REQUEST_CHANGE: 'PAYMENT_REQUEST_CHANGE',
  PAYMENT_REQUEST_CHANGE_SUCCESS: 'PAYMENT_REQUEST_CHANGE_SUCCESS',
  PAYMENT_REQUEST_CHANGE_FAILED: 'PAYMENT_REQUEST_CHANGE_FAILED',

  DOWNLOAD_DATA: 'DOWNLOAD_DATA',
  DOWNLOAD_DATA_SUCCESS: 'DOWNLOAD_DATA_SUCCESS',
  DOWNLOAD_DATA_FAILED: 'DOWNLOAD_DATA_FAILED',
};

export const CHAT_ACTION = {
  SEND_ATTACHMENT: 'SEND_ATTACHMENT',
  SEND_ATTACHMENT_SUCCESS: 'SEND_ATTACHMENT_SUCCESS',
  SEND_ATTACHMENT_FAILED: 'SEND_ATTACHMENT_FAILED',

  GET_CUSTOMER_INFO_COMMUNICATION: 'GET_CUSTOMER_INFO_COMMUNICATION',
  GET_CUSTOMER_INFO_COMMUNICATION_SUCCESS: 'GET_CUSTOMER_INFO_COMMUNICATION_SUCCESS',
  GET_CUSTOMER_INFO_COMMUNICATION_FAILED: 'GET_CUSTOMER_INFO_COMMUNICATION_FAILED',

  SET_SOURCE_CHAT: 'SET_SOURCE_CHAT',
  SET_SOURCE_CHAT_SUCCESS: 'SET_SOURCE_CHAT_SUCCESS',
  SET_SOURCE_CHAT_FAILED: 'SET_SOURCE_CHAT_FAILED',

  SET_NEW_MESSAGE_CHAT_SUCCESS: 'SET_NEW_MESSAGE_CHAT_SUCCESS',

  UPDATE_SHIPMENT_CHAT: 'UPDATE_SHIPMENT_CHAT',
  UPDATE_SHIPMENT_CHAT_SUCCESS: 'UPDATE_SHIPMENT_CHAT_SUCCESS',
  UPDATE_SHIPMENT_CHAT_FAILED: 'UPDATE_SHIPMENT_CHAT_FAILED',

  LOGIN_FIREBASE: 'LOGIN_FIREBASE',
  SET_LIST_ACTIVE: 'SET_LIST_ACTIVE',
  SET_SOURCE_CHAT_OFF: 'SET_SOURCE_CHAT_OFF',
};
