export const AUTH_ACTION = {
  CHANGE_STATUS: 'CHANGE_STATUS',
  UPDATE_DATA: 'UPDATE_DATA',
  UPDATE_DATA_SUCCESS: 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_FAILURE: 'UPDATE_DATA_FAILURE',

  CUSTOMER_LOGIN: 'CUSTOMER_LOGIN',
  CUSTOMER_LOGIN_SUCCESS: 'CUSTOMER_LOGIN_SUCCESS',
  CUSTOMER_LOGIN_FAILURE: 'CUSTOMER_LOGIN_FAILURE',

  CUSTOMER_REGISTER: 'CUSTOMER_REGISTER',
  CUSTOMER_REGISTER_SUCCESS: 'CUSTOMER_REGISTER_SUCCESS',
  CUSTOMER_REGISTER_FAILURE: 'CUSTOMER_REGISTER_FAILURE',
  CUSTOMER_REGISTER_RESET_DATA: 'CUSTOMER_REGISTER_RESET_DATA',

  VERIFICATION_CODE: 'VERIFICATION_CODE',
  VERIFICATION_CODE_SUCCESS: 'VERIFICATION_CODE_SUCCESS',
  VERIFICATION_CODE_FAILURE: 'VERIFICATION_CODE_FAILURE',

  RESEND_CODE: 'RESEND_CODE',
  RESEND_CODE_SUCCESS: 'RESEND_CODE_SUCCESS',
  RESEND_CODE_FAILURE: 'RESEND_CODE_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  REQUEST_LINK_RESET: 'REQUEST_LINK_RESET',
  REQUEST_LINK_RESET_SUCCESS: 'REQUEST_LINK_RESET_SUCCESS',
  REQUEST_LINK_RESET_FAILURE: 'REQUEST_LINK_RESET_FAILURE',

  LOG_OUT: 'LOG_OUT',

  REQUEST_UPDATE_PHONE: 'REQUEST_UPDATE_PHONE',
  REQUEST_UPDATE_PHONE_SUCCESS: 'REQUEST_UPDATE_PHONE_SUCCESS',
  REQUEST_UPDATE_PHONE_FAILURE: 'REQUEST_UPDATE_PHONE_FAILURE',

  SELECT_ACCOUNT: 'SELECT_ACCOUNT',
  SELECT_ACCOUNT_SUCCESS: 'SELECT_ACCOUNT_SUCCESS',
  SELECT_ACCOUNT_FAILURE: 'SELECT_ACCOUNT_FAILURE',

  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
};

export const APP_ACTION = {
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  REQUIRE_LOGIN_PAGE: 'REQUIRE_LOGIN_PAGE',
  UPDATE_POSITION: 'UPDATE_POSITION',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_ADDRESS_MODAL: 'OPEN_ADDRESS_MODAL',
  CLOSE_ADDRESS_MODAL: 'CLOSE_ADDRESS_MODAL',
  CHANGED_COUNTRY: 'CHANGED_COUNTRY',
  CHANGE_COUNTRY_SUCCESS: 'CHANGE_COUNTRY_SUCCESS',
  SET_APP_DATA: 'SET_APP_DATA',
  GET_CONFIGURATION_APP: 'GET_CONFIGURATION_APP',
  GET_CONFIGURATION_APP_SUCCESS: 'GET_CONFIGURATION_APP_SUCCESS',
  GET_CONFIGURATION_APP_FAIL: 'GET_CONFIGURATION_APP_FAIL',
  CLEAR_ERROR: 'CLEAR_ERROR',
};

export const LISTING_ACTION = {
  GET_HANDLE_UNIT_DEFAULT: 'GET_HANDLE_UNIT_DEFAULT',
  GET_HANDLE_UNIT_DEFAULT_SUCCESS: 'GET_HANDLE_UNIT_DEFAULT_SUCCESS',
  GET_HANDLE_UNIT_DEFAULT_FAILED: 'GET_HANDLE_UNIT_DEFAULT_FAILED',

  GET_ADDITIONAL_SERVICES_DEFAULT: 'GET_ADDITIONAL_SERVICES_DEFAULT',
  GET_ADDITIONAL_SERVICES_DEFAULT_SUCCESS: 'GET_ADDITIONAL_SERVICES_DEFAULT_SUCCESS',
  GET_ADDITIONAL_SERVICES_DEFAULT_FAILED: 'GET_ADDITIONAL_SERVICES_DEFAULT_FAILED',

  GET_LOCATION_SERVICES_DEFAULT: 'GET_LOCATION_SERVICES_DEFAULT',
  GET_LOCATION_SERVICES_DEFAULT_SUCCESS: 'GET_LOCATION_SERVICES_DEFAULT_SUCCESS',
  GET_LOCATION_SERVICES_DEFAULT_FAILED: 'GET_LOCATION_SERVICES_DEFAULT_FAILED',

  GET_HANDLE_UNIT: 'GET_HANDLE_UNIT',
  GET_HANDLE_UNIT_SUCCESS: 'GET_HANDLE_UNIT_SUCCESS',
  GET_HANDLE_UNIT_FAILED: 'GET_HANDLE_UNIT_FAILED',

  GET_ADVERT_DESCRIPTION: 'GET_ADVERT_DESCRIPTION',
  GET_ADVERT_DESCRIPTION_SUCCESS: 'GET_ADVERT_DESCRIPTION_SUCCESS',
  GET_ADVERT_DESCRIPTION_FAILURE: 'GET_ADVERT_DESCRIPTION_FAILURE',

  REQUEST_BOOK_NOW: 'REQUEST_BOOK_NOW',
  REQUEST_BOOK_NOW_SUCCESS: 'REQUEST_BOOK_NOW_SUCCESS',
  REQUEST_BOOK_NOW_FAILURE: 'REQUEST_BOOK_NOW_FAILURE',

  GET_TRANSPORT_TYPES: 'GET_TRANSPORT_TYPES',
  GET_TRANSPORT_TYPES_SUCCESS: 'GET_TRANSPORT_TYPES_SUCCESS',
  GET_TRANSPORT_TYPES_FAILED: 'GET_TRANSPORT_TYPES_FAILED',

  GET_TRANSPORT_TYPES_DEFAULT: 'GET_TRANSPORT_TYPES_DEFAULT',
  GET_TRANSPORT_TYPES_DEFAULT_SUCCESS: 'GET_TRANSPORT_TYPES_DEFAULT_SUCCESS',
  GET_TRANSPORT_TYPES_DEFAULT_FAILED: 'GET_TRANSPORT_TYPES_DEFAULT_FAILED',

  GET_ADDITIONAL_SERVICES: 'GET_ADDITIONAL_SERVICES',
  GET_ADDITIONAL_SERVICES_SUCCESS: 'GET_ADDITIONAL_SERVICES_SUCCESS',
  GET_ADDITIONAL_SERVICES_FAILED: 'GET_ADDITIONAL_SERVICES_FAILED',

  LISTING_SAVE_DRAFT: 'LISTING_SAVE_DRAFT',
  LISTING_SAVE_DRAFT_SUCCESS: 'LISTING_SAVE_DRAFT_SUCCESS',
  LISTING_SAVE_DRAFT_FAILED: 'LISTING_SAVE_DRAFT_FAILED',

  LISTING_DISCARD_DRAFT: 'LISTING_DISCARD_DRAFT',
  LISTING_DISCARD_DRAFT_SUCCESS: 'LISTING_DISCARD_DRAFT_SUCCESS',
  LISTING_DISCARD_DRAFT_FAILED: 'LISTING_DISCARD_DRAFT_FAILED',

  SET_TEMP_BOOKING: 'SET_TEMP_BOOKING',

  LISTING_ITEMS_GET_QUOTE: 'LISTING_ITEMS_GET_QUOTE',
  LISTING_ITEMS_GET_QUOTE_SUCCESS: 'LISTING_ITEMS_GET_QUOTE_SUCCESS',
  LISTING_ITEMS_GET_QUOTE_FAILED: 'LISTING_ITEMS_GET_QUOTE_FAILED',

  SET_TEMP_GET_QUOTE: 'SET_TEMP_GET_QUOTE',

  // STEP 2
  GET_ADDRESS_DATA: 'GET_ADDRESS_DATA',
  GET_ADDRESS_DATA_SUCCESS: 'GET_ADDRESS_DATA_SUCCESS',
  GET_ADDRESS_DATA_FAILURE: 'GET_ADDRESS_DATA_FAILURE',

  GET_DISTANCE_MATRIX: 'GET_DISTANCE_MATRIX',
  GET_DISTANCE_MATRIX_SUCCESS: 'GET_DISTANCE_MATRIX_SUCCESS',
  GET_DISTANCE_MATRIX_FAILURE: 'GET_DISTANCE_MATRIX_FAILURE',

  UPDATE_PICKUP_ADDRESS: 'UPDATE_PICKUP_ADDRESS',
  UPDATE_DESTINATION_ADDRESS: 'UPDATE_DESTINATION_ADDRESS',
  UPDATE_PICKUP_DATE: 'UPDATE_PICKUP_DATE',

  // STEP 3
  GET_SHIPMENT_DETAILS: 'GET_SHIPMENT_DETAILS',
  GET_SHIPMENT_DETAILS_SUCCESS: 'GET_SHIPMENT_DETAILS_SUCCESS',
  GET_SHIPMENT_DETAILS_FAILURE: 'GET_SHIPMENT_DETAILS_FAILURE',

  GET_SUMMARY: 'GET_SUMMARY',
  GET_SUMMARY_SUCCESS: 'GET_SUMMARY_SUCCESS',
  GET_SUMMARY_FAIURE: 'GET_SUMMARY_FAIURE',

  GET_LISTING_ITEMS: 'GET_LISTING_ITEMS',
  GET_LISTING_ITEMS_SUCCESS: 'GET_LISTING_ITEMS_SUCCESS',
  GET_LISTING_ITEMS_FAILURE: 'GET_LISTING_ITEMS_FAILURE',

  GET_ADDRESS: 'GET_ADDRESS',
  GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
  GET_ADDRESS_FAILURE: 'GET_ADDRESS_FAILURE',

  CREATE_QUOTE: 'CREATE_QUOTE',
  CREATE_QUOTE_SUCCESS: 'CREATE_QUOTE_SUCCESS',
  CREATE_QUOTE_FAILURE: 'CREATE_QUOTE_FAILURE',

  UPDATE_SHIPMENT: 'UPDATE_SHIPMENT',
  UPDATE_SHIPMENT_SUCCESS: 'UPDATE_SHIPMENT_SUCCESS',
  UPDATE_SHIPMENT_FAILURE: 'UPDATE_SHIPMENT_FAILURE',

  UPDATE_BASIC_SHIPMENT: 'UPDATE_BASIC_SHIPMENT',
  UPDATE_BASIC_SHIPMENT_SUCCESS: 'UPDATE_BASIC_SHIPMENT_SUCCESS',
  UPDATE_BASIC_SHIPMENT_FAILURE: 'UPDATE_BASIC_SHIPMENT_FAILURE',

  SAVE_LISTING_ITEMS: 'SAVE_LISTING_ITEMS',
  SAVE_LISTING_ITEMS_SUCCESS: 'SAVE_LISTING_ITEMS_SUCCESS',
  SAVE_LISTING_ITEMS_FAILURE: 'SAVE_LISTING_ITEMS_FAILURE',

  SAVE_LISTING_ADDRESS: 'SAVE_LISTING_ADDRESS',
  SAVE_LISTING_ADDRESS_SUCCESS: 'SAVE_LISTING_ADDRESS_SUCCESS',
  SAVE_LISTING_ADDRESS_FAILURE: 'SAVE_LISTING_ADDRESS_FAILURE',

  HANDLE_SEND: 'HANDLE_SEND',
  HANDLE_SEND_SUCCESS: 'HANDLE_SEND_SUCCESS',
  HANDLE_SEND_FAILED: 'HANDLE_SEND_FAILED',

  HANDLE_FIND: 'HANDLE_FIND',
  HANDLE_FIND_SUCESS: 'HANDLE_FIND_SUCESS',
  HANDLE_FIND_FAIL: 'HANDLE_FIND_SUCESS',

  SET_TITLE_SHIPMENT: 'SET_TITLE_SHIPMENT',

  SAVE_ADDRESS_AS_DRAFT: 'SAVE_ADDRESS_AS_DRAFT',
  SAVE_ADDRESS_AS_DRAFT_SUCCESS: 'SAVE_ADDRESS_AS_DRAFT_SUCCESS',
  SAVE_ADDRESS_AS_DRAFT_FAILED: 'SAVE_ADDRESS_AS_DRAFT_FAILED',

  SAVE_ADDRESS_QUOTE: 'SAVE_ADDRESS_QUOTE',
  SAVE_ADDRESS_QUOTE_SUCCESS: 'SAVE_ADDRESS_QUOTE_SUCCESS',
  SAVE_ADDRESS_QUOTE_FAILED: 'SAVE_ADDRESS_QUOTE_FAILED',

  SAVE_STATE_ADDRESS: 'SAVE_STATE_ADDRESS',

  SET_EDITING: 'SET_EDITING',
  SET_EDITING_SUCCESS: 'SET_EDITING_SUCCESS',

  GET_LOCATION_TYPES_DEFAULT: 'GET_LOCATION_TYPES_DEFAULT',
  GET_LOCATION_TYPES_DEFAULT_SUCCESS: 'GET_LOCATION_TYPES_DEFAULT_SUCCESS',
  GET_LOCATION_TYPES_DEFAULT_FAILED: 'GET_LOCATION_TYPES_DEFAULT_FAILED',

  EDITING_STEP2: 'EDITING_STEP2',

  UN_LIST: 'UN_LIST',
  UN_LIST_FAILED: 'UN_LIST_FAILED',
  UN_LIST_SUCCESS: 'UN_LIST_SUCCESS',

  GET_DELETE_REASON: 'GET_DELETE_REASON',
  GET_DELETE_REASON_SUCCESS: 'GET_DELETE_REASON_SUCCESS',
  GET_DELETE_REASON_FAIL: 'GET_DELETE_REASON_FAIL',

  DELETE_ALL: 'DELETE_ALL',
  DELETE_ALL_FAILED: 'DELETE_ALL_FAILED',
  DELETE_ALL_SUCCESS: 'DELETE_ALL_SUCCESS',

  DELETE_RELATED: 'DELETE_RELATED',
  DELETE_RELATED_FAILED: 'DELETE_RELATED_FAILED',
  DELETE_RELATED_SUCCESS: 'DELETE_RELATED_SUCCESS',

  UPLOAD_PHOTO_SHIPMENT: 'UPLOAD_PHOTO_SHIPMENT',
  UPLOAD_PHOTO_SHIPMENT_SUCCESS: 'UPLOAD_PHOTO_SHIPMENT_SUCCESS',
  UPLOAD_PHOTO_SHIPMENT_FAIL: 'UPLOAD_PHOTO_SHIPMENT_FAIL',

  DELETE_PHOTO_SHIPMENT: 'DELETE_PHOTO_SHIPMENT',
  DELETE_PHOTO_SHIPMENT_SUCCESS: 'DELETE_PHOTO_SHIPMENT_SUCCESS',
  DELETE_PHOTO_SHIPMENT_FAIL: 'DELETE_PHOTO_SHIPMENT_FAIL',

  UPDATING_ADDRESS: 'UPDATING_ADDRESS',
  SET_DATA_ADDRESS_UPDATING: 'SET_DATA_ADDRESS_UPDATING',
  SET_DATA_ADDRESS_UPDATING_SUCCESS: 'SET_DATA_ADDRESS_UPDATING_SUCCESS',

  REMOVE_ADDRESS_PHOTO: 'REMOVE_ADDRESS_PHOTO',
  UPDATE_STATUS_ADDRESS_UPDATING: 'UPDATE_STATUS_ADDRESS_UPDATING',

  EDIT_PICKUP_ADDRESS: 'EDIT_PICKUP_ADDRESS',
  EDIT_PICKUP_ADDRESS_SUCCESS: 'EDIT_PICKUP_ADDRESS_SUCCESS',
  EDIT_PICKUP_ADDRESS_FAIL: 'EDIT_PICKUP_ADDRESS_FAIL',

  HANDLE_AFTER_EDIT_PICKUP_ADDRESS: 'HANDLE_AFTER_EDIT_PICKUP_ADDRESS',
  HANDLE_AFTER_EDIT_PICKUP_ADDRESS_SUCCESS: 'HANDLE_AFTER_EDIT_PICKUP_ADDRESS_SUCCESS',
  HANDLE_AFTER_EDIT_PICKUP_ADDRESS_FAIL: 'HANDLE_AFTER_EDIT_PICKUP_ADDRESS_FAIL',

  HANDLE_AFTER_EDIT_DESTINATION_ADDRESS: 'HANDLE_AFTER_EDIT_DESTINATION_ADDRESS',
  HANDLE_AFTER_EDIT_DESTINATION_ADDRESS_SUCCESS: 'HANDLE_AFTER_EDIT_DESTINATION_ADDRESS_SUCCESS',
  HANDLE_AFTER_EDIT_DESTINATION_ADDRESS_FAIL: 'HANDLE_AFTER_EDIT_DESTINATION_ADDRESS_FAIL',

  EDIT_DESTINATION_ADDRESS: 'EDIT_DESTINATION_ADDRESS',
  EDIT_DESTINATION_ADDRESS_SUCCESS: 'EDIT_DESTINATION_ADDRESS_SUCCESS',
  EDIT_DESTINATION_ADDRESS_FAIL: 'EDIT_DESTINATION_ADDRESS_FAIL',
  SET_PHOTO_REMOVE: 'SET_PHOTO_REMOVE',

  EDITING_REMOVE_ITEM: 'EDITING_REMOVE_ITEM',
  EDITING_ADD_ITEM: 'EDITING_ADD_ITEM',
  EDITING_DUPLICATE_ITEM: 'EDITING_DUPLICATE_ITEM',

  EDITING_REMOVE_ADDRESS: 'EDITING_REMOVE_ADDRESS',
  EDITING_ADD_ADDRESS: 'EDITING_ADD_ADDRESS',
  EDITING_DUPLICATE_ADDRESS: 'EDITING_DUPLICATE_ADDRESS',
  EDITING_REPLACE_ADDRESS_DATA: 'EDITING_REPLACE_ADDRESS_DATA',

  UPDATE_LISTING_SHIPMENT_ITEMS: 'UPDATE_LISTING_SHIPMENT_ITEMS',
  UPDATE_LISTING_SHIPMENT_ITEMS_SUCCESS: 'UPDATE_LISTING_SHIPMENT_ITEMS_SUCCESS',
  UPDATE_LISTING_SHIPMENT_ITEMS_FAIL: 'UPDATE_LISTING_SHIPMENT_ITEMS_FAIL',

  UPDATE_LISTING_SHIPMENT_ADDRESSES: 'UPDATE_LISTING_SHIPMENT_ADDRESSES',
  UPDATE_LISTING_SHIPMENT_ADDRESSES_SUCCESS: 'UPDATE_LISTING_SHIPMENT_ADDRESSES_SUCCESS',
  UPDATE_LISTING_SHIPMENT_ADDRESSES_FAIL: 'UPDATE_LISTING_SHIPMENT_ADDRESSES_FAIL',

  UPDATE_DESTINATION_SHIPMENT_DETAIL: 'UPDATE_DESTINATION_SHIPMENT_DETAIL',
  UPDATE_DESTINATION_SHIPMENT_DETAIL_FAIL: 'UPDATE_DESTINATION_SHIPMENT_DETAIL_FAIL',
  UPDATE_DESTINATION_SHIPMENT_DETAIL_SUCCESS: 'UPDATE_DESTINATION_SHIPMENT_DETAIL_SUCCESS',
  UPDATE_DATA_FOR_MAP: 'UPDATE_DATA_FOR_MAP',

  GET_LIST_SHIPMENTS: 'GET_LIST_SHIPMENTS',
  GET_LIST_SHIPMENTS_SUCCESS: 'GET_LIST_SHIPMENTS_SUCCESS',
  GET_LIST_SHIPMENTS_FAIL: 'GET_LIST_SHIPMENTS_FAIL',

  SET_LOAD_MORE: 'SET_LOAD_MORE',
  SET_LOAD_MORE_SUCCESS: 'SET_LOAD_MORE_SUCCESS',
  SET_LOAD_MORE_FAILED: 'SET_LOAD_MORE_FAILED',

  ACCEPT_QUOTE: 'ACCEPT_QUOTE',
  ACCEPT_QUOTE_SUCCESS: 'ACCEPT_QUOTE_SUCCESS',
  ACCEPT_QUOTE_FAIL: 'ACCEPT_QUOTE_FAIL',

  REJECT_QUOTE: 'REJECT_QUOTE',
  REJECT_QUOTE_SUCCESS: 'REJECT_QUOTE_SUCCESS',
  REJECT_QUOTE_FAIL: 'REJECT_QUOTE_FAIL',

  GET_QUOTE_DETAIL: 'GET_QUOTE_DETAIL',
  GET_QUOTE_DETAIL_SUCCESS: 'GET_QUOTE_DETAIL_SUCCESS',
  GET_QUOTE_DETAIL_FAILED: 'GET_QUOTE_DETAIL_FAILED',

  GET_REASONS_REJECT_QUOTE: 'GET_REASONS_REJECT_QUOTE',
  GET_REASONS_REJECT_QUOTE_SUCCESS: 'GET_REASONS_REJECT_QUOTE_SUCCESS',
  GET_REASONS_REJECT_QUOTE_FAILED: 'GET_REASONS_REJECT_QUOTE_FAILED',

  GET_REASONS_CANCEL_BOOKING: 'GET_REASONS_CANCEL_BOOKING',
  GET_REASONS_CANCEL_BOOKING_SUCCESS: 'GET_REASONS_CANCEL_BOOKING_SUCCESS',
  GET_REASONS_CANCEL_BOOKING_FAILED: 'GET_REASONS_CANCEL_BOOKING_FAILED',

  SET_FIELD_QUERY: 'SET_FIELD_QUERY',
  SET_FIELD_QUERY_SUCCESS: 'SET_FIELD_QUERY_SUCCESS',
  SET_FIELD_QUERY_FAIL: 'SET_FIELD_QUERY_FAIL',

  SET_DATA_FOR_QUERY: 'SET_DATA_FOR_QUERY',
  SET_DATA_FOR_QUERY_SUCCESS: 'SET_DATA_FOR_QUERY_SUCCESS',
  SET_DATA_FOR_QUERY_FAIL: 'SET_DATA_FOR_QUERY_FAIL',

  SET_CURRENT_STEP: 'SET_CURRENT_STEP',
  SET_CURRENT_STEP_SUCCESS: 'SET_CURRENT_STEP_SUCCESS',
  SET_CURRENT_STEP_FAIL: 'SET_CURRENT_STEP_FAIL',

  SET_PIN: 'SET_PIN',
  SET_PIN_SUCCESS: 'SET_PIN_SUCCESS',
  SET_PIN_FAILED: 'SET_PIN_FAILED',

  CANCEL_BOOKING: 'CANCEL_BOOKING',
  CANCEL_BOOKING_SUCCESS: 'CANCEL_BOOKING_SUCCESS',
  CANCEL_BOOKING_FAIL: 'CANCEL_BOOKING_FAIL',

  BOOK_AGAIN: 'BOOK_AGAIN',
  BOOK_AGAIN_SUCCESS: 'BOOK_AGAIN_SUCCESS',
  BOOK_AGAIN_FAIL: 'BOOK_AGAIN_FAIL',

  REDIRECT_MANAGEMENT_SHIPMENTS: 'REDIRECT_MANAGEMENT_SHIPMENTS',
  REDIRECT_MANAGEMENT_SHIPMENTS_SUCCESS: 'REDIRECT_MANAGEMENT_SHIPMENTS_SUCCESS',
  REDIRECT_MANAGEMENT_SHIPMENTS_FAIL: 'REDIRECT_MANAGEMENT_SHIPMENTS_FAIL',

  DELETE_SHIPMENT_DATA: 'DELETE_SHIPMENT_DATA',
  DELETE_SHIPMENT_DATA_SUCCESS: 'DELETE_SHIPMENT_DATA_SUCCESS',
  DELETE_SHIPMENT_DATA_FAIL: 'DELETE_SHIPMENT_DATA_FAIL',

  UPDATE_DRAFT_ITEMS: 'UPDATE_DRAFT_ITEMS',
  UPDATE_DRAFT_ITEMS_SUCCESS: 'UPDATE_DRAFT_ITEMS_SUCCESS',
  UPDATE_DRAFT_ITEMS_FAIL: 'UPDATE_DRAFT_ITEMS_FAIL',

  UPDATE_DRAFT_ADDRESS: 'UPDATE_DRAFT_ADDRESS',
  UPDATE_DRAFT_ADDRESS_SUCCESS: 'UPDATE_DRAFT_ADDRESS_SUCCESS',
  UPDATE_DRAFT_ADDRESS_FAIL: 'UPDATE_DRAFT_ADDRESS_FAIL',

  SET_TRANSPORT_TYPE_ID: 'SET_TRANSPORT_TYPE_ID',
};

export const PROGRESS_ACTION = {
  GET_PROGRESS: 'GET_PROGRESS',
  GET_PROGRESS_SUCCESS: 'GET_PROGRESS_SUCCESS',
  GET_PROGRESS_FAIL: 'GET_PROGRESS_FAIL',

  UPDATE_PROGRESS: 'UPDATE_PROGRESS',
  UPDATE_PROGRESS_SUCCESS: 'UPDATE_PROGRESS_SUCCESS',
  UPDATE_PROGRESS_FAIL: 'UPDATE_PROGRESS_FAIL',

  UPLOAD_PROGRESS_ATTACHMENT: 'UPLOAD_PROGRESS_ATTACHMENT',
  UPLOAD_PROGRESS_ATTACHMENT_SUCCESS: 'UPLOAD_PROGRESS_ATTACHMENT_SUCCESS',
  UPLOAD_PROGRESS_ATTACHMENT_FAIL: 'UPLOAD_PROGRESS_ATTACHMENT_FAIL',

  UPLOAD_DISPATCHED_ATTACHMENT: 'UPLOAD_DISPATCHED_ATTACHMENT',
  UPLOAD_DISPATCHED_ATTACHMENT_SUCCESS: 'UPLOAD_DISPATCHED_ATTACHMENT_SUCCESS',
  UPLOAD_DISPATCHED_ATTACHMENT_FAIL: 'UPLOAD_DISPATCHED_ATTACHMENT_FAIL',

  DELETE_PROGRESS_ATTACHMENT: 'DELETE_PROGRESS_ATTACHMENT',
  DELETE_PROGRESS_ATTACHMENT_SUCCESS: 'DELETE_PROGRESS_ATTACHMENT_SUCCESS',
  DELETE_PROGRESS_ATTACHMENT_FAIL: 'UPLOAD_PROGRESS_ATTACHMENT_FAIL',
};

export const NOTIFICATION_ACTION = {
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  GET_NOTIFICATION_SUCCESS: 'GET_NOTIFICATION_SUCCESS',
  GET_NOTIFICATION_FAILED: 'GET_NOTIFICATION_FAILED',

  GET_NOTIFICATION_LOAD_MORE: 'GET_NOTIFICATION_LOAD_MORE',
  GET_NOTIFICATION_LOAD_MORE_SUCCESS: 'GET_NOTIFICATION_LOAD_MORE_SUCCESS',
  GET_NOTIFICATION_LOAD_MORE_FAILED: 'GET_NOTIFICATION_LOAD_MORE_FAILED',

  GET_NOTIFICATION_DETAIL: 'GET_NOTIFICATION_DETAIL',
  GET_NOTIFICATION_DETAIL_SUCCESS: 'GET_NOTIFICATION_DETAIL_SUCCESS',
  GET_NOTIFICATION_DETAIL_FAILED: 'GET_NOTIFICATION_DETAIL_FAILED',

  MARK_AS_READ_NOTIFICATION: 'MARK_AS_READ_NOTIFICATION',
  MARK_AS_READ_NOTIFICATION_SUCCESS: 'MARK_AS_READ_NOTIFICATION_SUCCESS',
  MARK_AS_READ_NOTIFICATION_FAILED: 'MARK_AS_READ_NOTIFICATION_FAILED',

  GET_TOTAL_UNREAD_NOTIFICATION: 'GET_TOTAL_UNREAD_NOTIFICATION',
  GET_TOTAL_UNREAD_NOTIFICATION_SUCCESS:
    'GET_TOTAL_UNREAD_NOTIFICATION_SUCCESS',
  GET_TOTAL_UNREAD_NOTIFICATION_FAILED: 'GET_TOTAL_UNREAD_NOTIFICATION_FAILED',
};

export const PAYMENT_ACTION = {
  GET_PAYMENT: 'GET_PAYMENT',
  GET_PAYMENT_SUCCESS: 'GET_PAYMENT_SUCCESS',
  GET_PAYMENT_FAILED: 'GET_PAYMENT_FAILED',

  REQUEST_CHANGE_PAYMENT_METHOD: 'REQUEST_CHANGE_PAYMENT_METHOD',
  REQUEST_CHANGE_PAYMENT_METHOD_SUCCESS: 'REQUEST_CHANGE_PAYMENT_METHOD_SUCCESS',
  REQUEST_CHANGE_PAYMENT_METHOD_FAILED: 'REQUEST_CHANGE_PAYMENT_METHOD_FAILED',

  AMEND_PAYMENT_METHOD: 'AMEND_PAYMENT_METHOD',
  AMEND_PAYMENT_METHOD_SUCCESS: 'AMEND_PAYMENT_METHOD_SUCCESS',
  AMEND_PAYMENT_METHOD_FAILED: 'AMEND_PAYMENT_METHOD_FAILED',

  UPLOAD_PROOF_PAYMENT_METHOD: 'UPLOAD_PROOF_PAYMENT_METHOD',
  UPLOAD_PROOF_PAYMENT_METHOD_SUCCESS: 'UPLOAD_PROOF_PAYMENT_METHOD_SUCCESS',
  UPLOAD_PROOF_PAYMENT_METHOD_FAILED: 'UPLOAD_PROOF_PAYMENT_METHOD_FAILED',

  DELETE_PROOF_PAYMENT_METHOD: 'DELETE_PROOF_PAYMENT_METHOD',
  DELETE_PROOF_PAYMENT_METHOD_SUCCESS: 'DELETE_PROOF_PAYMENT_METHOD_SUCCESS',
  DELETE_PROOF_PAYMENT_METHOD_FAILED: 'DELETE_PROOF_PAYMENT_METHOD_FAILED',

  COFIRM_COMPLETED_PAYMENT_METHOD: 'COFIRM_COMPLETED_PAYMENT_METHOD',
  COFIRM_COMPLETED_PAYMENT_METHOD_SUCCESS: 'COFIRM_COMPLETED_PAYMENT_METHOD_SUCCESS',
  COFIRM_COMPLETED_PAYMENT_METHOD_FAILED: 'COFIRM_COMPLETED_PAYMENT_METHOD_FAILED'
};

export const COMMUNICATION_ACTION = {
  CREATE_CONNECTION_CHAT: 'CREATE_CONNECTION_CHAT',
  UPDATE_DATA_CHAT: 'UPDATE_DATA_CHAT',
  SET_COMMUNICATION_DATA_TYPE_1: 'SET_COMMUNICATION_DATA_TYPE_1',
  SET_COMMUNICATION_DATA_TYPE_2: 'SET_COMMUNICATION_DATA_TYPE_2',
  SET_COMMUNICATION_DATA_TYPE_3: 'SET_COMMUNICATION_DATA_TYPE_3',
  SET_COMMUNICATION_DATA_TYPE_4: 'SET_COMMUNICATION_DATA_TYPE_4',

  SEND_ATTACHMENT: 'SEND_ATTACHMENT',
  SEND_ATTACHMENT_SUCCESS: 'SEND_ATTACHMENT_SUCCESS',
  SEND_ATTACHMENT_FAILED: 'SEND_ATTACHMENT_FAILED',

  SET_NEW_MESSAGE_CHAT: 'SET_NEW_MESSAGE_CHAT',

  DOWNLOAD_DATA: 'DOWNLOAD_DATA',
  DOWNLOAD_DATA_SUCCESS: 'DOWNLOAD_DATA_SUCCESS',
  DOWNLOAD_DATA_FAILED: 'DOWNLOAD_DATA_FAILED',

  UPDATE_SHIPMENT_CHAT: 'UPDATE_SHIPMENT_CHAT',
  UPDATE_SHIPMENT_CHAT_SUCCESS: 'UPDATE_SHIPMENT_CHAT_SUCCESS',
  UPDATE_SHIPMENT_CHAT_FAILED: 'UPDATE_SHIPMENT_CHAT_FAILED',

  LOGIN_FIREBASE: 'LOGIN_FIREBASE',
  SET_LIST_ACTIVE: 'SET_LIST_ACTIVE',
  LOGOUT_FIREBASE: 'LOGOUT_FIREBASE',
  SET_SOURCE_CHAT_OFF: 'SET_SOURCE_CHAT_OFF',

};
